//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjNetCore.Modules.Core.Content
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AjNetCore.Modules.Core.Content.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete your own account..
        /// </summary>
        public static string AdminTryOwnAccountDelete
        {
            get
            {
                return ResourceManager.GetString("AdminTryOwnAccountDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t inactive your own account..
        /// </summary>
        public static string AdminTryOwnAccountInactive
        {
            get
            {
                return ResourceManager.GetString("AdminTryOwnAccountInactive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;Password&apos; should match to &apos;Confirm Password&apos;..
        /// </summary>
        public static string BothPasswordMatch
        {
            get
            {
                return ResourceManager.GetString("BothPasswordMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid forgot password token or token already expired..
        /// </summary>
        public static string InvalidForgotPasswordToken
        {
            get
            {
                return ResourceManager.GetString("InvalidForgotPasswordToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You did not sign in correctly or your account is temporarily disabled..
        /// </summary>
        public static string InvalidLogin
        {
            get
            {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid site selected..
        /// </summary>
        public static string InvalidSiteSelected
        {
            get
            {
                return ResourceManager.GetString("InvalidSiteSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language record has been deleted..
        /// </summary>
        public static string LanguageRecordDelete
        {
            get
            {
                return ResourceManager.GetString("LanguageRecordDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated..
        /// </summary>
        public static string PasswordUpdated
        {
            get
            {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your profile has been successfully updated..
        /// </summary>
        public static string ProfileUpdated
        {
            get
            {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total {0} record(s) has been activated..
        /// </summary>
        public static string RecordActivate
        {
            get
            {
                return ResourceManager.GetString("RecordActivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total {0} record(s) has been deleted..
        /// </summary>
        public static string RecordDelete
        {
            get
            {
                return ResourceManager.GetString("RecordDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total {0} record(s) has been deactivated..
        /// </summary>
        public static string RecordInactivate
        {
            get
            {
                return ResourceManager.GetString("RecordInactivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record not found. Please try again..
        /// </summary>
        public static string RecordNotFound
        {
            get
            {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record has been successfully saved..
        /// </summary>
        public static string RecordSaved
        {
            get
            {
                return ResourceManager.GetString("RecordSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select at least one item from list..
        /// </summary>
        public static string SelectAtLeastOneItemFromList
        {
            get
            {
                return ResourceManager.GetString("SelectAtLeastOneItemFromList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated successfully. Please login with your new password..
        /// </summary>
        public static string SuccessResetPassword
        {
            get
            {
                return ResourceManager.GetString("SuccessResetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} already used with other records..
        /// </summary>
        public static string UniqueRecord
        {
            get
            {
                return ResourceManager.GetString("UniqueRecord", resourceCulture);
            }
        }
    }
}
